version: 1
task: tichu_card_identity
names:
  0: black10
  1: black2
  2: black3
  3: black4
  4: black5
  5: black6
  6: black7
  7: black8
  8: black9
  9: blacka
  10: blackj
  11: blackk
  12: blackq
  13: blue10
  14: blue2
  15: blue3
  16: blue4
  17: blue5
  18: blue6
  19: blue7
  20: blue8
  21: blue9
  22: bluea
  23: bluej
  24: bluek
  25: blueq
  26: dog
  27: dragon
  28: green10
  29: green2
  30: green3
  31: green4
  32: green5
  33: green6
  34: green7
  35: green8
  36: green9
  37: greena
  38: greenj
  39: greenk
  40: greenq
  41: mahjong
  42: phoenix
  43: red10
  44: red2
  45: red3
  46: red4
  47: red5
  48: red6
  49: red7
  50: red8
  51: red9
  52: reda
  53: redj
  54: redk
  55: redq

