version: 2
task: tichu_card_identity
names:
  0: 10-sword
  1: 2-sword
  2: 3-sword
  3: 4-sword
  4: 5-sword
  5: 6-sword
  6: 7-sword
  7: 8-sword
  8: 9-sword
  9: ace-sword
  10: jack-sword
  11: king-sword
  12: queen-sword
  13: 10-pagoda
  14: 2-pagoda
  15: 3-pagoda
  16: 4-pagoda
  17: 5-pagoda
  18: 6-pagoda
  19: 7-pagoda
  20: 8-pagoda
  21: 9-pagoda
  22: ace-pagoda
  23: jack-pagoda
  24: king-pagoda
  25: queen-pagoda
  26: dog
  27: dragon
  28: 10-jade
  29: 2-jade
  30: 3-jade
  31: 4-jade
  32: 5-jade
  33: 6-jade
  34: 7-jade
  35: 8-jade
  36: 9-jade
  37: ace-jade
  38: jack-jade
  39: king-jade
  40: queen-jade
  41: mahjong
  42: phoenix
  43: 10-star
  44: 2-star
  45: 3-star
  46: 4-star
  47: 5-star
  48: 6-star
  49: 7-star
  50: 8-star
  51: 9-star
  52: ace-star
  53: jack-star
  54: king-star
  55: queen-star
